project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    logo: "pic/manylang.png"
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Projects
        menu: 
          - href: calls.qmd
            text: Call for Projects
          - href: projects.qmd
            text: Projects
      - href: https://forms.gle/9mHjddrMFGzJzVLa8
        text: Feedback
      - text: Membership
        menu: 
          - href: join.qmd
            text: Join and Help
          - href: https://canvas.psysciacc.org
            text: Canvas

      - text: "Policies"
        menu: 
        - cocpolicy.qmd
        - peoplepolicy.qmd
        - studypolicy.qmd
        - authorpolicy.qmd
        - partners.qmd
    tools:
        - icon: github
          href:  https://github.com/many-languages/many-languages.github.io

format:
  html:
    theme: simplex
    css: styles.css
    toc: true
    toc-depth: 4
    toc-title: Contents

editor: visual

